# Generated by Django 4.2.13 on 2024-11-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
